#jswone ct properties
ctp.admin.projectKey=${CTP-ADMIN-PROJECTKEY}
ctp.admin.clientId=${CTP-ADMIN-CLIENT-ID}
ctp.admin.clientSecret=${CTP-ADMIN-CLIENTSECRET}
ctp.authUrl=https://auth.australia-southeast1.gcp.commercetools.com
ctp.apiUrl=https://api.australia-southeast1.gcp.commercetools.com
#ctp.admin.scopes=manage_project:one_ecom_dev
ctp.admin.scopes=${CTP-ADMIN-SCOPES:manage_project:jswone_ecom_dev_ps}

ctp.anon.clientId=${CTP-REGISTERED-CLIENTID}
ctp.anon.clientSecret=${CTP-REGISTERED-CLIENTSECRET}
#ctp.anon.scopes=view_categories:one_ecom_dev manage_my_payments:one_ecom_dev create_anonymous_token:one_ecom_dev manage_my_orders:one_ecom_dev manage_my_profile:one_ecom_dev view_published_products:one_ecom_dev manage_my_shopping_lists:one_ecom_dev
ctp.anon.scopes=${CTP-REGISTERED-SCOPES:view_categories:jswone_ecom_dev_ps manage_my_payments:jswone_ecom_dev_ps create_anonymous_token:jswone_ecom_dev_ps manage_my_orders:jswone_ecom_dev_ps manage_my_profile:jswone_ecom_dev_ps view_published_products:jswone_ecom_dev_ps manage_my_shopping_lists:jswone_ecom_dev_ps}


jwt.secret=${JWT-SECRET}

#Freight charge storage
freight.charge.table.name=${FREIGHT-CHARGE-TABLE-NAME:freight_charge_table_qa}
product.store.table.name=${PRODUCT-STORE-TABLE-NAME:product_store_dev}
categoryInfo.store.table.name=product_category_store
####CORS Configurations
#CORS.AllowedOrigin=https://qa.msme.jswone.in
CORS.AllowedOrigin=https://dev1.msme.jswone.in
CORS.AllowedOriginPatterns=http://localhost:*,https://*.msme.jswone.in,https://www.jswonemsme.com,https://jswonemsme.com,/swagger-ui.html,/swagger-ui/**,/v3/api-docs/**,/swagger-resources/**
CORS.AllowedHeaders=Authorization,Cache-Control,Content-Type,access_token,X-Request-ID
CORS.AllowedMethods=HEAD,GET,POST

#attribute group storage
attribute.group.table.name=${ATTRIBUTE-GROUP-TABLE-NAME:attribute_group_table_qa}

# measurement service
#rest.service.measurementService.url=https://qa.msme.jswone.in/measurement-service
rest.service.measurementService.url=https://dev1.msme.jswone.in/measurement-service
rest.internal.service.measurementService.url=${MEASUREMENT-SERVICE-CLOUD-RUN-URL}/measurement-service
rest.service.measurementService.endpoint.calculateMeasurement=/unit-of-measure/calculate-measurement
rest.service.measurementService.endpoint.uomDetailsEndpoint=/unit-of-measure/{productTypeKey}
rest.service.measurementService.endpoint.uomsDetailsEndpoint=/unit-of-measure/list

#Auth Service
#rest.service.authService.url=https://qa.msme.jswone.in/auth
rest.service.authService.url=https://dev1.msme.jswone.in/auth
rest.service.authService.genericToken=/generic/token
rest.service.authService.validateToken=/validate

#filter types
filter.type.selection=BRAND,GRADE,AWS_CODE,BASE_MATERIAL
filter.type.range=THICKNESS,WIDTH,LENGTH,DIAMETER

# Parting Charge
addtionalCharges.partingCharge.datastore.entity=${PARTING-CHARGE-TABLE:parting_charge_table_dev}

#Pincode Channel
pincode.serviceability.table.name=${CHANNEL-PINCODE-GROUP:channel_serviceability_table_qa}

#product-sku double attributes
product.sku.double.attributes=THICKNESS,WIDTH,LENGTH,DIAMETER

# Generic Token
rest.service.generic.token = ${SYSTEM-USER-JWT-TOKEN}

lineItem.executor.pool.size=20


#spring.cloud.gcp.datastore.project-id=${GCP-PROJ-ID:modular-bucksaw-305821}
spring.cloud.gcp.datastore.project-id=${GCP-PROJ-ID:jswone-dev}


#Price Service
#rest.service.priceService.url=https://qa.msme.jswone.in/pricing/additionalCharge
rest.service.priceService.url=https://dev1.msme.jswone.in/pricing/additionalCharge
rest.service.priceService.internal.url=${PRICING-SERVICE-CLOUD-RUN-URL}/pricing/additionalCharge
rest.service.priceService.bending.charge=/bendingBinding
rest.service.priceService.bending.charges=/bendingBinding/charges



# Cloud SQL specific properties
spring.cloud.gcp.sql.instance-connection-name=${CLOUD-SQL-CONNECTION-NAME}
spring.cloud.gcp.sql.database-name=${HISTORICAL-DB-NAME}
spring.cloud.gcp.sql.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Database connection properties
spring.datasource.url=jdbc:postgresql://${HISTORICAL-DB-IP}/${HISTORICAL-DB-NAME}
spring.datasource.jdbc-url=jdbc:postgresql://${HISTORICAL-DB-IP}/${HISTORICAL-DB-NAME}
spring.datasource.username=${HISTORICAL_DB_USER_NAME}
spring.datasource.password=${HISTORICAL_DB_PASSWORD}

#Buy-Again properties
buy.again.list.size=50
buy.again.home.size=3

ct.connection.timeout.seconds=200
ct.write.timeout.seconds=60
ct.read.timeout.seconds=120
ct.error.retry.count=3

#cache config
cached.category.list=a0e2db77-7629-48f3-8fca-9dd0ebaa6bc1
cache.ttl=${CACHE-TTL}

#uom data storage
measurement.data.table.name=${MEASUREMENT-DATA-TABLE-NAME}

# material master
material.master.access.token=${MATERIAL_MASTER_ACCESS_TOKEN}
master.data.admin.api.key=${MASTER-DATA-ADMIN-PRODUCT-SERVICE-API-KEY:210864a1-14f2-4272-85ef-74793872f698}
material.master.base.url=${MATERIAL_MASTER_BASE_URL:https://master-data-admin.jsw1msme.in}
master.data.service.base.url=${MASTER_DATA_SERVICE_CLOUD_RUN_URL:https://master-data.jsw1msme.in}
mm.categoryInfo.url=/master_data_admin/api/material_master/v1/search?mmid=
master.data.service.moq.url=/master_data_service/api/v1/material/moq
master.data.service.api.key=${MASTER-DATA-PRODUCT-SERVICE-API-KEY:f201c868-581c-4bde-baab-860d595fa4bd}
material.master.admin.client.id=${MATERIAL_MASTER_ADMIN_PRODUCT_SERVICE_CLIENT_ID:421ff64d-7aaa-47c1-9370-33a075471ce7}
master.data.service.client.id=${MASTER_DATA_SERVICE_PRODUCT_SERVICE_CLIENT_ID:f8e5dbc8-eae9-4b38-9ec1-5674682b7df0}

entity.tmt.bb.charge-group = bending_bundling_charge_qa

order.service.base.url=${ORDER-SERVICE-CLOUD-RUN-URL}
order.service.historical.sku.endpoint=/order-service/requirement/buy-again/sku

#Auto Product
auto.product.failure.channel.id=${PRODUCT-CATEGORY-FAILURE-SLACK-CHANNEL:C073CRKAM3J}
product.category.store.table.name=product_category_validity_table
auto.product.creation.subscription=${AUTO-PRODUCT-MASTERS-SUBSCRIPTION:masters-auto-product-event-ccp-dev-sub}
pdp.breadcrumbs.enabled=${PDP_BREADCRUMBS_ENABLED:true}

#Tax Rate Table
entity.tax-rate-group = product_tax_rate_table_qa

#Salesforce CT Sync Service
auto.product.creation.salesforce.ctSync.url=${SALESFORCE-SERVICE-CLOUD-RUN-URL:https://salesforce-sync-service-qa-01-nonjw7c6va-el.a.run.app}/data-sync/product/add-product/salesforce


pricing.service.base.url=${PRICING-ENGINE-SERVICE-CLOUD-RUN-URL:https://pricing-qa.onejswmsme.in}
pricing.service.fetch.price.endpoint=/price-orchestrator/api/v1/pricing/priceList
pricing.service.api.key=${PRICING-ENGINE-PRODUCT-SERVICE-API-KEY:2cadb302-947b-4b4d-9fbd-076c8734bc35}
pricing.engine.integration.enabled=${PRICING-ENGINE-ENABLE-FLAG:true}
pricing.error.slack.channel.id=C071AFG6LP2
CHANNEL-API-KEY-MAPPINGS=[{"distributorCtId":"e4895bc9-44f6-4d54-b671-7503166890ae","vendorMasterId":"V1146-1147-JOPL-1147","sellerUniqueId":"JD001","channelKey":"JODLMH001"},{"distributorCtId":"c2af3774-baef-48b3-bff1-6f96070f3db6","vendorMasterId":"V1146-1322-JOPL-1322","sellerUniqueId":"JD002","channelKey":"JODLKA001"},{"distributorCtId":"93f12800-d747-43f8-b2e9-6fa99bd5bc4a","vendorMasterId":"V1146-1323-JOPL-1323","sellerUniqueId":"JD003","channelKey":"JODLTN001"}]
product.projection.search.enabled=${PRODUCT_PROJECTION_SEARCH_ENABLED}
plp.datastore.filter.enabled=${PLP_DATASTORE_FILTER_ENABLED:false}

product.service.strapi.enabled=${STRAPI_ENABLED:true}
product.service.user.strapi.enabled=${STRAPI_LIST_OF_USERS}
#API KEY PRODUCT SERVICE
api.key.product.service=${PRODUCT_SERVICE_API_KEY:ProductService-v1-7gd82kfjw5m3x9lzqypvoah64tsr0cnbxu1ejvdkf2h7w3miolbcqzfn6yp45t8}
product.service.pdp.journey.enabled=${PDP_JOURNEY_ENABLED:true}
buy.again.moq.enable=${ENABLE_MOQ_BUY_AGAIN:false}

#Teams Alert
pricing.error.teams.channel.workflow.url=${PRICING_ERROR_CHANNEL_WORKFLOW_URL:https://default1250f2eb4784422398dcd6e3344556.5c.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/f998f4bfe9044da685e1d7a49dd65d50/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=TmXxuowUQgHVDjavZSk-WL8VWmJp_vXXZpyRwxsrGJA}
auto.product.failure.teams.channel.workflow.url=${AUTO_PRODUCT_ERROR_CHANNEL_WORKFLOW_URL:https://default1250f2eb4784422398dcd6e3344556.5c.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/cb4a5516efa243d8995dc0fb0bb0ccb6/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=fjG6NMDaVwWyh4tB7uuaiuDfRtEcch_5M7_FV5LfaxM}
product.selector.datastore.flag=${PRODUCT_SELECTOR_DATA_STORE_FLAG:true}