spring.application.name=central-commerce-service
server.servlet.context-path=/central_commerce
server.port=9091

logging.level.root=INFO
logging.pattern.console=%clr(%X{requestId}){cyan} %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr(%X{process_id}){magenta} %clr(---){faint} %clr([ %t]){faint}  %clr(%logger{36}){cyan} %clr(:){faint} %m%n

spring.servlet.multipart.enabled=true

# Threshold after which files are written to disk.

spring.servlet.multipart.file-size-threshold=2KB

# Max file size.

spring.servlet.multipart.max-file-size=1MB

# Max Request Size

spring.servlet.multipart.max-request-size=1MB


jsw.service.connection.timeout=60000
jsw.service.connection.readTimeout=60000

springfox.documentation.swagger.v2.path=/product/swagger.json

spring.cloud.gcp.datastore.enabled=true
spring.main.allow-bean-definition-overriding=true

spring.cloud.gcp.project-id=${GCP-PROJ-ID:modular-bucksaw-305821}
spring.cloud.gcp.credentials.encoded-key=${GCP-CREDENTIALS}

# Cloud SQL specific properties
spring.cloud.gcp.sql.instance-connection-name=${CLOUD-SQL-CONNECTION-NAME}
spring.cloud.gcp.sql.database-name=${HISTORICAL-DB-NAME}
spring.cloud.gcp.sql.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Database connection properties
spring.datasource.url=jdbc:postgresql://${HISTORICAL-DB-IP}/${HISTORICAL-DB-NAME}
spring.datasource.jdbc-url=jdbc:postgresql://google/${HISTORICAL-DB-NAME}?cloudSqlInstance=${CLOUD-SQL-CONNECTION-NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=${HISTORICAL_DB_USER_NAME}&password=${HISTORICAL_DB_PASSWORD}
spring.datasource.username=${HISTORICAL_DB_USER_NAME}
spring.datasource.password=${HISTORICAL_DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver

#Buy-Again properties
buy.again.list.size=50
buy.again.home.size=3
ct.connection.timeout.seconds=200
ct.write.timeout.seconds=60
ct.read.timeout.seconds=120
ct.error.retry.count=3

spring.aop.auto=true
datastore.table.user.token=user_auth_token_store

#HEADER Config
server.max-http-header-size=65536

product.service.strapi.enabled=${STRAPI_ENABLED:true}

product.service.user.strapi.enabled=${STRAPI_LIST_OF_USERS}

api.key.commerce.service={X-API-KEY-COMMERCE:abc}