spring.application.name=central-commerce-service
spring.main.banner-mode=console
server.port=9091

# Redis connection
central.commerce.redis.host=${CENTRAL_COMMERCE_REDIS_HOST_NAME:redis-16699.c31624.asia-south1-1.gcp.cloud.rlrcp.com}
central.commerce.redis.port=${CENTRAL_COMMERCE_REDIS_PORT:16699}
central.commerce.redis.password=${CENTRAL_COMMERCE_REDIS_PASSWORD:3456N97$Nz$Hj}
central.commerce.redis.username=${CENTRAL_COMMERCE_REDIS_USERNAME:app_central_commerce_qa}
central.commerce.redis.timeout=60000
central.commerce.redis.poolsize=${CENTRAL_COMMERCE_REDIS_POOLSIZE:12}
central.commerce.redis.max-idle=${CENTRAL_COMMERCE_REDIS_MAX_IDLE:12}
central.commerce.redis.min-idle=${CENTRAL_COMMERCE_REDIS_MIN_IDLE:8}
redis.profile=qa
central.commerce.redis.cache_manager.enable=${CENTRAL_COMMERCE_REDIS_CACHE_MANAGER_ENABLE:false}
central.commerce.cloud.cache.certificate=${REDIS_CERTIFICATE:REDIS_CACHE_CERTIFICATE}

# Buy Againx`
buy.again.warmup.max-entries=${BUY_AGAIN_WARMUP_MAX_ENTRIES:10000}
pdp.journey.enabled=${PDP_JOURNEY_ENABLED:true}

logging.level.root=INFO

spring.servlet.multipart.enabled=true

# Threshold after which files are written to disk.

spring.servlet.multipart.file-size-threshold=2KB

# Max file size.

spring.servlet.multipart.max-file-size=1MB

# Max Request Size

spring.servlet.multipart.max-request-size=1MB


jsw.service.connection.timeout=60000
jsw.service.connection.readTimeout=60000

springfox.documentation.swagger.v2.path=/product/swagger.json

spring.cloud.gcp.datastore.enabled=true
spring.main.allow-bean-definition-overriding=true

spring.cloud.gcp.project-id=${GCP-PROJ-ID:modular-bucksaw-305821}
spring.cloud.gcp.credentials.encoded-key=${GCP-CREDENTIALS}

#Buy-Again properties
buy.again.list.size=50
buy.again.home.size=3
ct.connection.timeout.seconds=200
ct.write.timeout.seconds=60
ct.read.timeout.seconds=120
ct.error.retry.count=3

spring.aop.auto=true
datastore.table.user.token=user_auth_token_store

#HEADER Config
server.max-http-header-size=65536

#CORS Configurations
CORS.AllowedOriginPatterns=http://localhost:*,https://*.msme.jswone.in,https://www.jswonemsme.com,https://jswonemsme.com
CORS.AllowedHeaders=Authorization,Cache-Control,Content-Type,access_token,x-api-key,traceId
CORS.AllowedMethods=HEAD,GET,POST,DELETE
jsw.executor.queue.capacity=50
jsw.executor.max.pool.size=14
msme.base.url=${MSME-BASE-URL:https://qa.msme.jswone.in}

#jwt
jwt.secret=${JWT-SECRET}
jwt.system.user.token=${SYSTEM-USER-JWT-TOKEN}

#jswone ct properties
ctp.admin.projectKey=${CTP-ADMIN-PROJECTKEY:one_ecom_dev}
ctp.admin.clientId=${CTP-ADMIN-CLIENT-ID:t1THqbvDVBzLEtfpNAJRNLnG}
ctp.admin.clientSecret=${CTP-ADMIN-CLIENTSECRET:y7s4r_3cAwmwhP9OKSTfy0dPvyYU8Ont}
ctp.authUrl=https://auth.australia-southeast1.gcp.commercetools.com
ctp.apiUrl=https://api.australia-southeast1.gcp.commercetools.com
ctp.admin.scopes=${CTP-ADMIN-SCOPES:manage_project:one_ecom_dev}

ctp.anon.clientId=${CTP-REGISTERED-CLIENTID:bkYIsUvWaH1qu2hf_8XujoF2}
ctp.anon.clientSecret=${CTP-REGISTERED-CLIENTSECRET:YJ9fd2oT23i8hjx_O5_R3vi2BDrsGZk_}
ctp.anon.scopes=${CTP-REGISTERED-SCOPES:view_categories:one_ecom_dev manage_my_payments:one_ecom_dev create_anonymous_token:one_ecom_dev manage_my_orders:one_ecom_dev manage_my_profile:one_ecom_dev view_published_products:one_ecom_dev manage_my_shopping_lists:one_ecom_dev}

#Auth Service
rest.service.authService.url=https://qa.msme.jswone.in/auth
rest.service.authService.validate=/validate
rest.service.authService.genericToken=/generic/token

auth.base.url = https://qa-oms.msme.jswone.in/auth2-service
http.connection.socket.timeout = 50000

# gcp pub sub config
spring.cloud.gcp.pubsub.enabled=true
spring.cloud.gcp.pubsub.credentials.encoded-key=${GCP-CREDENTIALS}
spring.cloud.gcp.pubsub.project-id=${GCP-PROJ-ID:jswone-qa-356112}

# CT Thread pool config
exe.ct.thread.prefix=CTConnect-
exe.ct.queue.capacity=60
exe.ct.keepalive=10
exe.ct.max.pool.size=60
exe.ct.core.pool.size=10

#data store properties
spring.cloud.gcp.datastore.project-id=${GCP-PROJ-ID:jswone-qa-356112}
spring.cloud.gcp.datastore.credentials.encoded-key=${GCP-CREDENTIALS}
# Specify the path of the OpenAPI documentation 33AALFT4479K1ZL,

#product-sku double attributes
product.sku.double.attributes=THICKNESS,WIDTH,LENGTH,DIAMETER

api.key.commerce.service.web=${X-API-KEY-COMMERCE-WEB:CommerceServiceWeb-v1-9xblf2tjw6h5y7k3vd0qpoamz48srnycluej8dgw9mf12vhz5tocqk7xpyl3b6fd}


#timeouts
service.connection.timeout=60000
service.connection.readTimeout=60000

#logging pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%t] [TRACE_ID=%X{traceId}] [SPAN_ID=%X{spanId}] %-5level %logger{36} - %msg%n

#Central Catalogue
central.catalogue.base.url=https://catalogue-central.qa.jsw1msme.in
central.catalogue.generic.search.endpoint=/catalogue_search/api/v1/search/product
central.catalogue.bulk.mmid.endpoint=/catalogue_search/api/v2/product/bulk/mmids
central.catalogue.api.key=${CENTRAL-COMMERCE-CATALOGUE-API-KEY:611d61db-339f-483b-a854-7f35cc085155}
central.catalogue.client.id=${CENTRAL-COMMERCE-CATALOGUE-CLIENT-ID:fabb7514-1d0b-44ea-a6f5-897346a96099}

# EXCLUDED PRODUCT ATTRIBUTES
catalogue.excluded-attributes=\
created_at,\
created_by,\
product_title,\
product_id,\
slug,\
id,\
standard,\
meta_title,\
delivery time,\
meta_description

# UNIT MAP KEY UNIT VALUE
catalogue.unit-map.thickness=mm
catalogue.unit-map.width=mm
catalogue.unit-map.length=mm
catalogue.unit-map.diameter=mm
catalogue.unit-map.web_depth=mm
catalogue.unit-map.flange_width=mm
catalogue.unit-map.sectional_weight=kg/m
catalogue.unit-map.leg=mm

# INCLUDED PRODUCT ATTRIBUTES
catalogue.included-attributes=\
grade,\
sub_grade,\
brand,\
sub_brand,\
aws_code

#Catalogue category
catalogue.category.base.url=${CATALOGUE_CATEGORY_BASE_URL:https://catalogue-central.qa.jsw1msme.in/catalogue-admin-service/api/v1/category-client}
catalogue.category.api.key=${CATALOGUE_CATEGORY_API_KEY:7cbfc9d1-027f-46cd-90b9-db1288ee8d85}
catalogue.category.client.id=${CATALOGUE_CATEGORY_CLIENT_ID:69ab4721-0c01-475c-94bd-765f9beeb978}

#Historical DB Config
spring.cloud.gcp.sql.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.cloud.gcp.sql.instance-connection-name=${CLOUD_SQL_CONNECTION_NAME:jswone-qa-356112:asia-south1:oms-db-qa}
spring.cloud.gcp.sql.database-name=${HISTORICAL_DB_NAME:historical_db}
spring.datasource.url=jdbc:postgresql://${HISTORICAL_DB_IP:10.252.16.3}:5432/${HISTORICAL_DB_NAME:historical_db}
spring.datasource.username=${HISTORICAL_DB_USER_NAME:anuragw}
spring.datasource.password=${HISTORICAL_POSTGRES_PASSWORD:EbPtI|HBr}