#jswone ct properties
ctp.admin.projectKey=${CTP-ADMIN-PROJECTKEY}
ctp.admin.clientId=${CTP-ADMIN-CLIENT-ID}
ctp.admin.clientSecret=${CTP-ADMIN-CLIENTSECRET}
ctp.authUrl=https://auth.australia-southeast1.gcp.commercetools.com
ctp.apiUrl=https://api.australia-southeast1.gcp.commercetools.com
ctp.admin.scopes=${CTP-ADMIN-SCOPES:manage_project:jswone-msme-prod}

ctp.anon.clientId=${CTP-REGISTERED-CLIENTID}
ctp.anon.clientSecret=${CTP-REGISTERED-CLIENTSECRET}
ctp.anon.scopes=${CTP-REGISTERED-SCOPES:view_published_products:jswone-msme-prod view_shipping_methods:jswone-msme-prod manage_my_orders:jswone-msme-prod view_tax_categories:jswone-msme-prod manage_my_payments:jswone-msme-prod manage_my_shopping_lists:jswone-msme-prod manage_my_profile:jswone-msme-prod create_anonymous_token:jswone-msme-prod view_categories:jswone-msme-prod}

#ct properties
customer.group.custom.type.key=jsw_customer_group_custom_type
customer.custom.type.key=jsw_customer_custom_type
root.customer.group.key=rootOrganization
jswOne.customer.group.key=jswOneOrganization
b2b.customer.group.key=b2b
msme.customer.group.key=msme
address.custom.type.key=jsw-customer-address
others.industry.type=others

#error
#registration errors
email.duplicate=E-mail ID already in use, please sign in with your user id
phone.duplicate=This phone number is already existing in our customer list kindly login with your registered mobile number as user ID
gstin.duplicate=Provided GSTIN is already registered with us. Please input a different one or login with the registered mobile number/email-id as user-id
verify.phone.error= This phone number is not verified. Please verify to continue with registration.
customergroup.add.error= unable to create customer group

#OTP errors
user.reset.error=Kindly register yourself to proceed further for JSW One journey
phone.number.error=PhoneNumber Not Found
max.try.reached=Maximum try Reached
invalid.otp=Invalid OTP

#Login errors
invalid.credentials.message=Kindly input correct credentials

product.store.table.name=${PRODUCT-STORE-TABLE-NAME:product_store_prod}
categoryInfo.store.table.name=product_category_store
#UserId update message
email.update.success = Email Updated successfully.
email.update.token = Update Email Token generated successfully.
token.error= Invalid token

#Profile msgs
address.success =Your address is updated successfully
profile.success =Your profile is updated successfully
verify.userid.error= This user id is not verified. Please verify to continue with update process.

#Product Search
product.pinned.item.count=5
product.recent.searched.count=3
product.recent.searched.limit=5
product.popular.searched.limit=5
product.search.suggetion.limit=5
product.search.numericcheck.prefix=x
product.search.numericcheck.suffix=y

#Categories search
categories.search.empty=No categories found
categories.search.error=Unable to fetch category
categories.search.success=category found
categories.search.category.na=na
categories.name.empty=na
categories.description.empty=na
categories.key.empty=na
grade.search.success=subgrade found
grade.search.error=no subgrade found

#Suggest API
suggest.search.error=No suggestions found
suggestapi.userinput.length.three=3

#Customer Product Msgs
cust.pdt.invalid.message=Invalid request data
cust.pdt.unauthorized.messge=Unauthorized Access
cust.pdt.update.message=Adding the data to the existing list.
cust.pdt.remove.message=Removing the data from the existing list.
cust.pdt.create.message=No data found. Creating a new one.
cust.pdt.not.found.messsage=Required data is not found.

#StorageException
storage.file.error= unable to add/retrieve File
storage.file.precondition=Invalid required fields
storage.profile.extensions=jpeg,jpg,png
storage.profile.size=1

#dev url for email verify link
hostURL=https://www.jswonemsme.com/customer/verifyNewEmail?token=#tokenValue

emailVerifyTokenTTLMinutes = 100
storeKey.business= business

categories.maximum.limit=100
products.maximum.limit=500

default.max.price.addition=1000
isProd = true

#email notification
cart.base.url=https://www.jswonemsme.com/cart/
customer.base.url=https://www.jswonemsme.com/customer/
email.link=notification/sendEmail
assisted.sales.email.link=sales/data
sales.to.email=sales@jswonemsme.com
notification.freight.email.to=product@jswone.in,operations@jswonemsme.com
operations.to.email=operations@jswonemsme.com
notification.base.url=https://www.jswonemsme.com/notification
email.end.point=/email/send/freight
price.tier.email.end.point=/email/send/price-tier


jwt.secret=${JWT-SECRET}

#Freight charge storage
freight.charge.table.name=${FREIGHT-CHARGE-TABLE-NAME:freight_charge_table_prod}

#attribute group storage
attribute.group.table.name=${ATTRIBUTE-GROUP-TABLE-NAME:attribute_group_table_prod}


####CORS Configurations
CORS.AllowedOrigin=https://www.jswonemsme.com
CORS.AllowedOriginPatterns=https://www.jswonemsme.com,https://jswonemsme.com,/swagger-ui.html,/swagger-ui/**,/v3/api-docs/**,/swagger-resources/**
CORS.AllowedHeaders=Authorization,Cache-Control,Content-Type,access_token,X-Request-ID
CORS.AllowedMethods=HEAD,GET,POST

### measurement service
rest.service.measurementService.url=https://www.jswonemsme.com/measurement-service
rest.internal.service.measurementService.url=${MEASUREMENT-SERVICE-CLOUD-RUN-URL}/measurement-service
rest.service.measurementService.endpoint.calculateMeasurement=/unit-of-measure/calculate-measurement
rest.service.measurementService.endpoint.uomDetailsEndpoint=/unit-of-measure/{productTypeKey}
rest.service.measurementService.endpoint.uomsDetailsEndpoint=/unit-of-measure/list

# auth service
rest.service.authService.url=https://www.jswonemsme.com/auth
rest.service.authService.genericToken =/generic/token
rest.service.authService.validateToken=/validate

#Parting charge storage
addtionalCharges.partingCharge.datastore.entity=${PARTING-CHARGE-TABLE:parting_charge_table_prod}

#Pincode Channel
pincode.serviceability.table.name=${CHANNEL-PINCODE-GROUP:channel_serviceability_table_prod}

# Generic Token
rest.service.generic.token = ${SYSTEM-USER-JWT-TOKEN}

#filter types
filter.type.selection=BRAND,GRADE,AWS_CODE,BASE_MATERIAL
filter.type.range=THICKNESS,WIDTH,LENGTH,DIAMETER

#product-sku double attributes
product.sku.double.attributes=THICKNESS,WIDTH,LENGTH,DIAMETER

freight.auth.url=https://www.jswonemsme.com/auth/validate

lineItem.executor.pool.size=30

spring.cloud.gcp.datastore.project-id=${GCP-PROJ-ID:modular-bucksaw-305821}

#Price Service
rest.service.priceService.url=https://www.jswonemsme.com/pricing/additionalCharge
rest.service.priceService.internal.url=${PRICING-SERVICE-CLOUD-RUN-URL}/pricing/additionalCharge
rest.service.priceService.bending.charge=/bendingBinding
rest.service.priceService.bending.charges=/bendingBinding/charges

google.matrix.api.cache.expiry=60


data.importer.bucket=${DATA-IMPORTER-BUCKET:data-exporter-bucket-prod}


new.notification.base.url=https://www.jswonemsme.com/notification-api/v1/
notification.v1.internal.url=${NOTIFICATION-NODE-JS-SERVICE-CLOUD-RUN-URL}/notification-api/v1/
notification.mail.endpoint=notification/send
new.notification.service.token=${NOTIFICATION-SERVICE-TOKEN}

spring.datasource.url=jdbc:postgresql://${HISTORICAL-DB-IP}/${HISTORICAL-DB-NAME}
spring.datasource.username=${HISTORICAL_DB_USER_NAME}
spring.datasource.password=${HISTORICAL_DB_PASSWORD}

#Buy-Again properties
buy.again.list.size=50
buy.again.home.size=3

ct.connection.timeout.seconds=200
ct.write.timeout.seconds=60
ct.read.timeout.seconds=120
ct.error.retry.count=3

#uom data storage
measurement.data.table.name=${MEASUREMENT-DATA-TABLE-NAME}

# material master
material.master.access.token=${MATERIAL_MASTER_ACCESS_TOKEN}
master.data.admin.api.key=${MASTER-DATA-ADMIN-PRODUCT-SERVICE-API-KEY}
material.master.base.url=${MATERIAL_MASTER_BASE_URL}
material.master.admin.client.id=${MATERIAL_MASTER_ADMIN_PRODUCT_SERVICE_CLIENT_ID}
master.data.service.base.url=${MASTER_DATA_SERVICE_CLOUD_RUN_URL:https://master-data.jsw1msme.com}
master.data.service.client.id=${MASTER_DATA_SERVICE_PRODUCT_SERVICE_CLIENT_ID}
mm.categoryInfo.url=/master_data_admin/api/material_master/v1/search?mmid=
master.data.service.moq.url=/master_data_service/api/v1/material/moq
master.data.service.api.key=${MASTER-DATA-PRODUCT-SERVICE-API-KEY}

#cashBack Service
cashback.service.base.url=${CASHBACK-SERVICE-CLOUD-RUN-URL}
cashback.pdp.static.response.url=/cashback-service/cashback/pdp
cashback.pdp.response.url=/cashback-service/cashback/pdp-price
cashback.cart.change.endpoint=/cashback-service/cashback/cart/change
cashback.enabled=${CASHBACK_ENABLED}
cashback.service.api.key=${CASHBACK-API-KEY}

#cache config
cached.category.list=17fdca08-8034-49c1-8ea2-90801ef351b9,0e76055e-df54-492f-b356-e63055847898,d468cc20-b6f4-4987-8076-3ebae65ed492,732257f2-1b39-483d-8dd5-4c3bd468c6b6,\
  5abf8e66-94ad-446a-8d7d-de7080c8daab,8b82b449-15d5-4893-babc-afbb24e30584,cf75c045-8255-48c6-9b77-8c5bdbd59ba7,\
  855f9998-14f4-4537-9ebc-95797a4cbede,248a98ed-1097-426d-af66-49c6a152f05f,8df3ad88-279a-425b-a09c-08b72b2f6506,e82bdd75-fea4-43f4-9b1e-b2e004ab41b6,\
  e38a410c-cc2f-4d91-a674-9d6a8bbc237a,6245202f-7902-40ef-abc0-786c80f98a15,91bdc10a-6634-4f02-85d5-a889c863bb4e,4e16a421-bc7d-4f87-a9bf-cc2925b75a12,\
  464a2676-7874-4e2e-9571-1be459158ca6,d7ba4655-aa88-4f50-b8d8-76b76c6ed3ff,45504b76-e9af-415f-976c-0bc312d6fd4b,c208a646-1959-46df-b116-212d2b7c9b1f,\
  7d8eea8f-1656-437f-89be-aeb3ba49d96a,5b49e6bf-72f2-4f76-94c8-92a15da5b1b9,bdd5a61f-64c7-4910-83e8-fd807cad64d0,5f4bc45b-e8c2-49f5-b35f-885eae96ecd7,\
  6dff00b5-7feb-49b8-bf22-a15fca3543ff,763467b0-1ab9-4311-9c1b-7aeaab87cb60,6292cbf8-e511-4f4a-9ccc-febfd681fbf6,6210fe94-8969-4d52-997e-1505d634070f,\
  3727aa62-bfa6-403a-a1de-8c4cc0a5abaa,72f38a2d-48b6-42ab-9b8f-5a124c723d4f,47d17a13-e7da-4f45-a24c-3e1c62b90dc6,e6de00dc-1ed5-46cb-9601-279a05dd639e,\
  9017363b-7d27-43d5-8b9e-8f8f7ab73b41,283319c7-ce25-4057-9f5c-45ae8666c4c2,bbf0adbb-8c74-4fb8-ae25-8c4790485096,0cb095bd-06d0-4e5d-bcbd-09f7317d559b,\
  5f7d5903-bd79-4253-97ef-964152be38d8,776d6cb0-7d89-41d4-bd37-77c8d28cf3ea,2db36f02-75ba-4ce1-bc13-6a9b7e81c5b5,678391ea-3da9-4d22-bed0-0f95d229df49,\
  2eb3bfc7-2d87-4b96-9c8b-7f804e542bb2,4824c6e9-159a-4b2d-ab61-bce10de5c998,e8f19363-902d-4b93-88f0-54da576c137c,fd6f8ffb-7bd5-4ec9-a525-d2e3769d6375,\
  c3d46539-61db-4e32-9c78-39165f341ce0,d83b479c-c2c3-4b77-9ed9-8d02e6c287e5,e8e169e2-54ab-46e4-bc2b-3710232ea067,c8e7b898-8162-40c9-a102-c740e4df2944,\
  0fd37eaa-8d99-40f4-827c-21c24350f649,2277d1ca-32cd-440e-bbf3-c840faf1e868,78ab6dc3-f9fe-4717-b617-2ce92be92c11,73cfee66-4b24-4056-9035-3c81b6457e5a,\
  5e36186d-161f-4ae7-9737-b31cba1226c1,a0b6e7c2-c202-4a57-9787-59c64115f77e,5928d795-cbe5-426f-8904-5321b6bf86fa,9d6a9fd8-70f6-4fd4-b71b-900f75a0cfbc

cache.ttl=${CACHE-TTL}

entity.tmt.bb.charge-group = bending_bundling_charge_prod

order.service.base.url=${ORDER-SERVICE-CLOUD-RUN-URL}
order.service.historical.sku.endpoint=/order-service/requirement/buy-again/sku

#Auto Product
auto.product.failure.channel.id=${PRODUCT-CATEGORY-FAILURE-SLACK-CHANNEL}
product.category.store.table.name=product_category_validity_table
auto.product.creation.subscription=${AUTO-PRODUCT-MASTERS-SUBSCRIPTION}
pdp.breadcrumbs.enabled=${PDP_BREADCRUMBS_ENABLED:true}

#Tax Rate Table
entity.tax-rate-group = product_tax_rate_table_prod

#Salesforce CT Sync Service
auto.product.creation.salesforce.ctSync.url=${SALESFORCE-SERVICE-CLOUD-RUN-URL}/data-sync/product/add-product/salesforce

pricing.service.base.url=${PRICING-ENGINE-SERVICE-CLOUD-RUN-URL:https://pricing.jsw1msme.com}
pricing.service.fetch.price.endpoint=/price-orchestrator/api/v1/pricing/priceList
pricing.service.api.key=${PRICING-ENGINE-PRODUCT-SERVICE-API-KEY}
pricing.engine.integration.enabled=${PRICING-ENGINE-ENABLE-FLAG:false}
pricing.error.slack.channel.id=C070MMZV550
CHANNEL-API-KEY-MAPPINGS=[{"distributorCtId":"ac3da499-c364-4f71-afc9-b188ac0ba75f","vendorMasterId":"V1146-1147-JOPL-1147","sellerUniqueId":"JD001","channelKey":"JODLMH001"},{"distributorCtId":"a55d44f7-7910-4682-814f-9b850398279a","vendorMasterId":"V1146-1322-JOPL-1322","sellerUniqueId":"JD002","channelKey":"JODLKA001"},{"distributorCtId":"ac0c78b3-3aa5-45f0-87cf-9645aedb6f3d","vendorMasterId":"V1146-1323-JOPL-1323","sellerUniqueId":"JD003","channelKey":"JODLTN001"},{"distributorCtId":"2177473f-870b-4e23-9ab9-f36e3b12a427","vendorMasterId":"V1146-1324-JOPL-1324","sellerUniqueId":"JD006","channelKey":"JODLHR001"},{"distributorCtId":"ca73358a-b38c-4d1f-af97-494b4c359857","vendorMasterId":"V1146-1325-JOPL-1325","sellerUniqueId":"JD004","channelKey":"JODLDL001"},{"distributorCtId":"1b79c3b2-e057-4846-b26a-435bfdb47d86","vendorMasterId":"V1146-1326-JOPL-1326","sellerUniqueId":"JD007","channelKey":"JODLUP001"},{"distributorCtId":"528795b7-b138-42c3-a200-6ab6a49315f0","vendorMasterId":"V1146-1327-JOPL-1327","sellerUniqueId":"JD008","channelKey":"JODLAP001"},{"distributorCtId":"77f5625e-3eac-4a5d-90bc-9601289f997a","vendorMasterId":"V1146-1328-JOPL-1328","sellerUniqueId":"JD005","channelKey":"JODLTS001"},{"distributorCtId":"c0f061f0-975c-492c-a852-465149a40acb","vendorMasterId":"V1146-1329-JOPL-1329","sellerUniqueId":"JD011","channelKey":"JODLPB001"},{"distributorCtId":"40efc26e-a978-459a-83c1-89fadba93cd8","vendorMasterId":"V1146-1334-JOPL-1334","sellerUniqueId":"JD010","channelKey":"JODLRJ001"},{"distributorCtId":"0bc9ab31-98b0-4b30-8185-9769c3cb35ce","vendorMasterId":"V1146-1335-JOPL-1335","sellerUniqueId":"JD012","channelKey":"JODLMP001"},{"distributorCtId":"ac0527bc-943f-4dda-a56e-736aecb54522","vendorMasterId":"V1146-1336-JOPL-1336","sellerUniqueId":"JD013","channelKey":"JODLWB001"},{"distributorCtId":"628b10f8-ad4f-4903-b978-fda4bed78b2f","vendorMasterId":"V1146-1337-JOPL-1337","sellerUniqueId":"JD014","channelKey":"JODLHP001"},{"distributorCtId":"262c8bd6-0ef8-4de7-addf-0f5a50d57b95","vendorMasterId":"V1146-1338-JOPL-1338","sellerUniqueId":"JD015","channelKey":"JODLCG001"},{"distributorCtId":"8de85e22-c04c-4a34-bfd1-acb6eec8b589","vendorMasterId":"V1146-1629-JOPL-2000","sellerUniqueId":"JD016","channelKey":"JODLGJ001"}]
product.projection.search.enabled=${PRODUCT_PROJECTION_SEARCH_ENABLED}
plp.datastore.filter.enabled=${PLP_DATASTORE_FILTER_ENABLED}

product.service.strapi.enabled=${STRAPI_ENABLED:true}
product.service.user.strapi.enabled=${STRAPI_LIST_OF_USERS}

#API KEY PRODUCT SERVICE
api.key.product.service=${PRODUCT_SERVICE_API_KEY}

buy.again.moq.enable=${ENABLE_MOQ_BUY_AGAIN:false}
product.service.pdp.journey.enabled=${PDP_JOURNEY_ENABLED:true}

#Teams Alert
pricing.error.teams.channel.workflow.url=${PRICING_ERROR_CHANNEL_WORKFLOW_URL}
auto.product.failure.teams.channel.workflow.url=${AUTO_PRODUCT_ERROR_CHANNEL_WORKFLOW_URL}
product.selector.datastore.flag=${PRODUCT_SELECTOR_DATA_STORE_FLAG:true}