
server.servlet.context-path=/central_commerce
server.port=9091

logging.level.root=INFO

spring.servlet.multipart.enabled=true

# Threshold after which files are written to disk.

spring.servlet.multipart.file-size-threshold=2KB

# Max file size.

spring.servlet.multipart.max-file-size=1MB

# Max Request Size

spring.servlet.multipart.max-request-size=1MB


jsw.service.connection.timeout=60000
jsw.service.connection.readTimeout=60000

springfox.documentation.swagger.v2.path=/product/swagger.json

spring.cloud.gcp.datastore.enabled=true
spring.main.allow-bean-definition-overriding=true

spring.cloud.gcp.project-id=${GCP-PROJ-ID:modular-bucksaw-305821}
spring.cloud.gcp.credentials.encoded-key=${GCP-CREDENTIALS}

#Buy-Again properties
buy.again.list.size=50
buy.again.home.size=3
ct.connection.timeout.seconds=200
ct.write.timeout.seconds=60
ct.read.timeout.seconds=120
ct.error.retry.count=3

spring.aop.auto=true
datastore.table.user.token=user_auth_token_store

#HEADER Config
server.max-http-header-size=65536

product.service.strapi.enabled=${STRAPI_ENABLED:true}

product.service.user.strapi.enabled=${STRAPI_LIST_OF_USERS}

api.key.commerce.service={X-API-KEY-COMMERCE:abc}

#CORS Configurations
CORS.AllowedOriginPatterns=http://localhost:*,https://*.msme.jswone.in,https://www.jswonemsme.com,https://jswonemsme.com
CORS.AllowedHeaders=Authorization,Cache-Control,Content-Type,access_token
CORS.AllowedMethods=HEAD,GET,POST,DELETE
jsw.executor.queue.capacity=50
jsw.executor.max.pool.size=14
msme.base.url=${MSME-BASE-URL:https://qa.msme.jswone.in}
#jwt
jwt.secret=${JWT-SECRET}
jwt.system.user.token=${SYSTEM-USER-JWT-TOKEN}
#jswone ct properties
ctp.admin.projectKey=one_ecom_dev
ctp.admin.clientId=t1THqbvDVBzLEtfpNAJRNLnG
ctp.admin.clientSecret=y7s4r_3cAwmwhP9OKSTfy0dPvyYU8Ont
ctp.authUrl=https://auth.australia-southeast1.gcp.commercetools.com
ctp.apiUrl=https://api.australia-southeast1.gcp.commercetools.com
ctp.admin.scopes=manage_project:one_ecom_dev

ctp.anon.clientId=bkYIsUvWaH1qu2hf_8XujoF2
ctp.anon.clientSecret=YJ9fd2oT23i8hjx_O5_R3vi2BDrsGZk_
ctp.anon.scopes=view_categories:one_ecom_dev manage_my_payments:one_ecom_dev create_anonymous_token:one_ecom_dev manage_my_orders:one_ecom_dev manage_my_profile:one_ecom_dev view_published_products:one_ecom_dev manage_my_shopping_lists:one_ecom_dev

# Contentful
contentful.space-id=${CONTENTFUL-SPACE-ID:o0otttl8ele8}
contentful.environment= qa
contentful.access-token= ${CONTENTFUL-ACCESS-TOKEN}

# measurement service
rest.service.measurementService.url=${msme.base.url}/measurement-service
rest.service.measurementService.endpoint.calculateMeasurement=/unit-of-measure/calculate-measurement
rest.service.measurementService.endpoint.calculateMeasurements=/unit-of-measure/calculate-measurements
rest.service.measurementService.endpoint.getUomDetails=/unit-of-measure/list
measurementService.endpoint.calculateMeasurement=/unit-of-measure/calculate-measurement

#Auth Service
rest.service.authService.url=${msme.base.url}/auth
rest.service.authService.validate=/validate
rest.service.authService.genericToken=/generic/token

#Discount
rest.service.discountService.url=${msme.base.url}
rest.service.discountService.endpoint.close=/discounts/v2/close

#cart
rest.service.cart.url=${msme.base.url}
rest.service.cart.recalculate.discount.cart=/cart/discounts/recalculate
customer.cart.url =https://qa-ssr.msme.jswone.in/cart-detail

customer.payment.url=https://qa-ssr.msme.jswone.in/payment
customer.order.url=https://qa-ssr.msme.jswone.in/order-summary
productTaxURL=https://qa.msme.jswone.in/pricing/gst/sku-key
#oms
oms.client.url=https://qa-oms.msme.jswone.in/oms
#joms.client.url=https://dev-next.msme.jswone.in/joms/api
joms.client.url=https://qa-oms.msme.jswone.in/joms/api
joms.api.key=3f9a2b5f-7bd8-4a51-b11f-47b30decd925
#oms.client.url=https://qapreprod-oms.onejswmsme.in/oms
oms.internal.base.url=${OMS-INTERNAL-BASE-URL:https://qa-oms.msme.jswone.in/oms}
#oms.internal.base.url=${OMS-INTERNAL-BASE-URL:https://qapreprod-oms.onejswmsme.in/oms}
oms.customer.shipment.path=/shipment/order-number/
oms-system-token=${OMS-BEARER-TOKEN:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJpbnRlZ3JhdGlvbl91c2VyLnBheW1lbnRAanN3LmluIiwiYXV0aCI6IlJPTEVfVVNFUiIsImlhdCI6MTY5MDUyMTU4NiwiZXhwIjoxNzIyMDU3NTg2fQ.aGEHP1O8rHqVVoNXPv6HohZjO5QD9jIcmg_GL-nWWonGwcNDhyQF4uMZx7PTj7U_qx8Ow-NlvE18bYxpafrwIA}
oms-document-storage-bucket=${OMS-STORAGE-DOC-BUCKET:jsw-invoice-docs-qa}
auth.base.url = https://qa-oms.msme.jswone.in/auth2-service
#auth.base.url = https://qapreprod-oms.onejswmsme.in/auth2-service
#oms.auth.username =${OMS-AUTH-USER-NAME:ccp_oms@jsw.in}
#oms.auth.password =${OMS-AUTH-PASSWORD:oms}
#oms.client.http.connection.socket.timeout = 50000
http.connection.socket.timeout = 50000
oms.user.name=${OMS-AUTH-USER-NAME:ccp_oms@jsw.in}
oms.secret.token=${OMS-AUTH-PASSWORD:oms}
oms-system-token-webclient=${OMS-SYSTEM_TOKEN}

oms.sap.order.status.sync=/order/sap-order-details
oms.sap.order.document.upload=/documents/upload
oms.shipment.list.path=/shipment/listing/
oms.shipment.summary.path=/shipment/summary/
oms.order.paymentList.url=/payment/recordedTransaction
oms.planned.shipment.details.url=/plant-supply/requested-payments
oms.offomspayout.nodocuments.path=/off-oms-payout/nodocuments
oms.offomspayout.document.upload.path=/subscriber/offoms/documents/capture
cashbackrefund.batua.url=/buyer/refund/transactions
oms.sap.customer.code=/customer/getSAPCustomerCodeFromGstin
# gcp pub sub config
spring.cloud.gcp.pubsub.enabled=true
spring.cloud.gcp.pubsub.credentials.encoded-key=${GCP-CREDENTIALS}
spring.cloud.gcp.pubsub.project-id=${GCP-PROJ-ID:jswone-qa-356112}
#SAP
sap.base.url=${SAP_BASE_URL:https://pimwsysqa.jsw.in}
sap.invoice.url=/DocumentPDF
sap.service.username=${SAP-USERNAME:sdfsdfsdf}
sap.service.password=${SAP-PASSWORD:sdfsdfsdf}
sap.basic.token=${SAP_BASIC_TOKEN:dsfsdfsdfsfd}
sap.invoice.subscription=sap-plantsupply-document-qa-sub
sap.plant.supply.document.oms=sap-plant-supply-document-oms

#OMS DB Datasource
spring.cloud.gcp.sql.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.cloud.gcp.sql.instance-connection-name=jswone-qa-356112:asia-south1:master-db-qa
spring.cloud.gcp.sql.database-name=postgres
spring.datasource.jdbc-url=jdbc:postgresql://35.244.59.74/master_data
spring.datasource.username=divanshusharma
spring.datasource.password=O5Gbkk2K4T18
#Salesforce
sf-opportunity-storage-bucket=${SF-OPPORTUNITY-STORAGE-BUCKET:ct_sf_opportunity_data_qa}
sf-opportunity-storage-bucket-path=ct_sf_response_file/ct_sf_opportunity_response.xlsx
salesforce.user.grantType=${SALESFORCE-GRANT-TYPE:password}
salesforce.user.clientId= ${SALESFORCE-CLIENT-ID:3MVG9ZUGg10Hh224GhhTm_qyu2_U9Xs2YK_31FhfHv7csgYVsNYdGKfme3sdrOHBzmkxPi7rbaoix9EQEemfr}
salesforce.user.name= ${SALESFORCE-USER-NAME:integration.user@stetig.in.jsw.uat}
salesforce.user.password= ${SALESFORCE-USER-PASSWORD:JSW1@123V5zyNsAkVePDrsIbUw08v10E}
salesforce.user.clientSecret= ${SALESFORCE-CLIENT-SECRET:D612EF37A28B2CFEAEA2D9A9241C84188174EFBCF09565FFCA4DA2CF479A5058}
rest.salesforce.auth.endpoint=/services/oauth2/token
rest.salesforce.base.url=https://jswoneplatforms--uat.sandbox.my.salesforce.com
rest.salesforce.myrequirements.url=/services/apexrest/getCartOpportunity
rest.salesforce.order.opportunity.url=/services/apexrest/SfOrder
rest.salesforce.buy-again.base.url=/services/apexrest/skudata
order.opportunity.event.subscriber=${ORDER-OPPORTUNITY-CREATE-SUB:order-opportunity-event-qa-sub}
notification.base.url=${msme.base.url}/notification
order.email.notification.url=/email/send
salesforce.order.fetch.failure.notification.mail.to=v_shalin.shah@jsw.in,v_sindhu.nair@jsw.in
salesforce.order.fetch.failure.notification.mail.cc=cart-fetch-failure-no-aaaaf4rtyl6scfaajtvufrfhki@jsw-oneworkspace.slack.com
order.service.env=QA
#batua
batua.client.user=${BATUA-USERNAME}
batua.client.secret=${BATUA-SECRET}
batua.base.url=https://qa-oms.msme.jswone.in/batua
batua.balance.url=/balance
distributed.order.notification.mail.to=v_sindhu.nair@jsw.in,arnab.maity@jsw.in,gaurav.pal@jsw.in,v_shalin.shah@jsw.in,v_pradeep.aridass@jsw.in,shahaji.muley@jsw.in,aakash.prasad@jsw.in,parth.shah@jsw.in
internal.notification.mail.cc=aakash.aggarwal@jsw.in,kamaksh.gangani@jsw.in,shivam.rathi@jsw.in,shruti.garg@jsw.in,v_bhavesh.mhatre@jsw.in,v_pavithra@jsw.in,v_puneet.kundliya@jsw.in,chandrasekara.reddy@jsw.in,v_sindhu.nair@jsw.in,shahaji.muley@jsw.in,aakash.prasad@jsw.in,parth.shah@jsw.in
order.created.state.id=${ORDER-CREATED-STATE-ID:4c9212a0-a924-4fa3-8bc1-132dc5caeff0}
order.placed.state.id=${ORDER-PLACED-STATE-ID:ef4e3bd8-476c-4822-a577-eaa1a66868ea}
#PO Document
gcp.po.document.bucket=${GCP-DOCUMENT-BUCKET:order-docs-qa}
gcp.order-summary.document.bucket=${GCP-DOCUMENT-BUCKET:order-docs-qa}
signed.url.expiry.in.min=5

# CT Thread pool config
exe.ct.thread.prefix=CTConnect-
exe.ct.queue.capacity=60
exe.ct.keepalive=10
exe.ct.max.pool.size=60
exe.ct.core.pool.size=10

# New notification configuration
#new.notification.base.url=https://qa.msme.jswone.in/notification-api/v1/
new.notification.base.url=https://dev1.msme.jswone.in/notification-api/v1/

notification.v1.internal.url=${NOTIFICATION-NODE-JS-SERVICE-CLOUD-RUN-URL:https://qa.msme.jswone.in}/notification-api/v1/
new.notification.service.token=${NOTIFICATION-SERVICE-TOKEN:yHk8dLdWZKlA04c20ay8vddcfQ8+gYe7FrSb6YLkk0Q=}
notification.mail.endpoint=notification/send

##WHATSAPP Notification
fe.notification.whatsapp.internal.endpoint=${NOTIFICATION-NODE-JS-SERVICE-CLOUD-RUN-URL:https://qa.msme.jswone.in}/notification-api/v1/notification/send
fe.notification.whatsapp.endpoint=https://qa.msme.jswone.in/notification-api/v1/notification/send
fe.notification.secret.key=${FE-NOTIFICATION-SECRET-KEY-QA:yHk8dLdWZKlA04c20ay8vddcfQ8+gYe7FrSb6YLkk0Q=}

##Token Expiry channel
token.expiry.slack.channel=${TOKEN-EXPIRY-SLACK-CHANNEL:qa-application-token-expiry}

##material master
material.master.access.token=${MATERIAL_MASTER_ACCESS_TOKEN:sdfsdfsdsd}

#ledger service
ledger-service.base.url= ${LEDGER_SERVICE_BASE_URL:https://next.qa.jswone.in}
ledger-service.client.user =${LEDGER_SERVICE_USER:LSCLI3}
ledger-service.client.secret=${LEDGER_SERVICE_SECRET:LedgerService.CCP.$2b$12$G7YUOAcWoOM4mmq5uM3x.u1LzBvjgGBCl6BajMo2Ae7Yo9PC7Yyga}
ledger-service.enable.flag = ${LEDGER_SERVICE_FLAG:false}

erp.order.creation.enabled=${ERP_ORDER_CREATION_ENABLED:true}
erp.backward.flow.enabled=${BACKWARD_FLOW_NEW:true}

#Block OS for Sellers
block.os.sellers.list=${BLOCK-OS-FOR-SELLERS:V1723-2095-JOPL-2557,V1723-2094-JOPL-2556,V1723-2093-JOPL-2555}

#data store properties
spring.cloud.gcp.datastore.project-id=${GCP-PROJ-ID:jswone-qa-356112}
spring.cloud.gcp.datastore.credentials.encoded-key=${GCP-CREDENTIALS}
# Specify the path of the OpenAPI documentation 33AALFT4479K1ZL,
application-description=Order service is used for order functionality for SKU.
application-version=1

erp.enable.gstin.list=${LIST_OF_USERS:33AAACZ4322M2Z9,24AALCM9561A1ZH,33AADCS6230N1Z9,32ABBPE2153N1Z0,33AAACL1978K1ZC,29AVNPA9932H1Z6,33AALFT4479K1ZL}
freight.charge.tax.rate=${FREIGHT_CHARGE_TAX_RATE:0.18}

cashback.service.base.url=${CASHBACK-SERVICE-CLOUD-RUN-URL:https://qa.msme.jswone.in}
cashback.order.endpoint=/cashback-service/cashback/order
cashback.service.api.key=${CASHBACK-API-KEY:CashbackApiKey-v1 7rd589zs5lf486pf1ril6imb9giyvz8c7ab6e3l2sa5jxripeakh2nszcjzjdsg8}
rest.productService.url.line.item=${PRODUCT-SERVICE-CLOUD-RUN-URL:https://qa.msme.jswone.in}/cashback/line-item
cashback.enabled=${CASHBACK_ENABLED:false}

api.key.order.service=${ORDER_SERVICE_API_KEY:OrderService-v1-9xblf2tjw6h5y7k3vd0qpoamz48srnycluej8dgw9mf12vhz5tocqk7xpyl3b6fd}


zoho.flag.enabled=${ZOHO_ENABLED:true}

#SF connector details
outbound-connector.client.id = ${CCP_OUTBOUND_CONNECTOR_CLIENT_ID:CLIN6}
outbound-connector.client.secret = ${CCP_OUTBOUND_CONNECTOR_CLIENT_SECRET:CCP.Connector.cdbajvdut&%bBDAnnnsa}
outbound-connector.base.url= ${CCP_OUTBOUND_CONNECTOR_BASE_URL:http://external-connector-outbound.qa-01.svc.cluster.local}
order.service.connector.flag=${ORDER_SERVICE_CONNECTOR_FLAG:true}
dynamic.van.order.service.flag =${DYNAMIC_VAN_ORDER_SERVICE_FLAG:true}

#teams workflow url

token.expiry.teams.channel.workflow.url=${TOKEN_EXPIRY_TEAMS_CHANNEL_WORKFLOW_URL:https://default1250f2eb4784422398dcd6e3344556.5c.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/49797b4ff6db4311b91dfa5e5b0291fa/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=hdb9oVgrTATa7vqQIx-SBtvT3B-yNDSkNRUsqXqiLd0}

#CMS-Strapi
strapi.api.url=${STRAPI_CMS_BASE_URL:https://cms-msme-ext.qa.jswone.in/api/}
strapi.product.customer.config.endpoint=ccp-feature-flags

#Temporal Service
create.order.workflow.flag=${CREATE_ORDER_WORKFLOW_FLAG:true}
temporal.order.client.url=${TEMPORAL_ORDER_CLIENT_URL:https://tms.qa.jswone.in}
api.key.temporal.service=${X-API-KEY:c4a1c6f2-5e3b-4d8a-8f1e-2b7c9d3a6b10}

#product-sku double attributes
product.sku.double.attributes=THICKNESS,WIDTH,LENGTH,DIAMETER