#jswone ct properties
ctp.admin.projectKey=${CTP-ADMIN-PROJECTKEY}
ctp.admin.clientId=${CTP-ADMIN-CLIENT-ID}
ctp.admin.clientSecret=${CTP-ADMIN-CLIENTSECRET}
ctp.authUrl=https://auth.australia-southeast1.gcp.commercetools.com
ctp.apiUrl=https://api.australia-southeast1.gcp.commercetools.com
ctp.admin.scopes=${CTP-ADMIN-SCOPES:manage_project:one_ecom_dev}

ctp.anon.clientId=${CTP-REGISTERED-CLIENTID}
ctp.anon.clientSecret=${CTP-REGISTERED-CLIENTSECRET}
ctp.anon.scopes=${CTP-REGISTERED-SCOPES:view_categories:one_ecom_dev manage_my_payments:one_ecom_dev create_anonymous_token:one_ecom_dev manage_my_orders:one_ecom_dev manage_my_profile:one_ecom_dev view_published_products:one_ecom_dev manage_my_shopping_lists:one_ecom_dev}

jwt.secret=${JWT-SECRET}

#Freight charge storage
freight.charge.table.name=${FREIGHT-CHARGE-TABLE-NAME:freight_charge_table_qa}

#attribute group storage
attribute.group.table.name=${ATTRIBUTE-GROUP-TABLE-NAME:attribute_group_table_qa}
product.store.table.name=${PRODUCT-STORE-TABLE-NAME:product_store_qa}
categoryInfo.store.table.name=product_category_store

####CORS Configurations

CORS.AllowedOrigin=https://qa.msme.jswone.in
CORS.AllowedOriginPatterns=http://localhost:*,https://*.msme.jswone.in,https://www.jswonemsme.com,https://jswonemsme.com,/swagger-ui.html,/swagger-ui/**,/v3/api-docs/**,/swagger-resources/**
CORS.AllowedHeaders=Authorization,Cache-Control,Content-Type,access_token,X-Request-ID
CORS.AllowedMethods=HEAD,GET,POST

#measurement service

rest.service.measurementService.url=https://qa.msme.jswone.in/measurement-service
rest.internal.service.measurementService.url=${MEASUREMENT-SERVICE-CLOUD-RUN-URL}/measurement-service
rest.service.measurementService.endpoint.calculateMeasurement=/unit-of-measure/calculate-measurement
rest.service.measurementService.endpoint.uomDetailsEndpoint=/unit-of-measure/{productTypeKey}
rest.service.measurementService.endpoint.uomsDetailsEndpoint=/unit-of-measure/list

#auth service
rest.service.authService.url=https://qa.msme.jswone.in/auth
rest.service.authService.genericToken=/generic/token
rest.service.authService.validateToken=/validate

#email
notification.freight.email.to=jsw.testoperations@gmail.com,v_sreenivas.gundlapalli@jsw.in,v_sindhu.nair@jsw.in
notification.base.url=https://qa.msme.jswone.in/notification
email.end.point=/email/send/freight
price.tier.email.end.point=/email/send/price-tier

#filter types
filter.type.selection=BRAND,GRADE,AWS_CODE,BASE_MATERIAL
filter.type.range=THICKNESS,WIDTH,LENGTH,DIAMETER

# Parting Charge
addtionalCharges.partingCharge.datastore.entity=${PARTING-CHARGE-TABLE:parting_charge_table_qa}

#Pincode Channel
pincode.serviceability.table.name=${CHANNEL-PINCODE-GROUP:channel_serviceability_table_qa}

# Generic Token
rest.service.generic.token = ${SYSTEM-USER-JWT-TOKEN}

lineItem.executor.pool.size=25

spring.cloud.gcp.datastore.project-id=${GCP-PROJ-ID:modular-bucksaw-305821}

#Price Service
rest.service.priceService.url=https://qa.msme.jswone.in/pricing/additionalCharge
rest.service.priceService.internal.url=${PRICING-SERVICE-CLOUD-RUN-URL}/pricing/additionalCharge
rest.service.priceService.bending.charge=/bendingBinding
rest.service.priceService.bending.charges=/bendingBinding/charges

google.matrix.api.cache.expiry=60

data.importer.bucket=${DATA-IMPORTER-BUCKET:data-exporter-bucket-qa}

new.notification.base.url=https://qa.msme.jswone.in/notification-api/v1/
notification.v1.internal.url=${NOTIFICATION-NODE-JS-SERVICE-CLOUD-RUN-URL}/notification-api/v1/
notification.mail.endpoint=notification/send
new.notification.service.token=${NOTIFICATION-SERVICE-TOKEN}

# Database connection properties
spring.datasource.url=jdbc:postgresql://${HISTORICAL-DB-IP}/${HISTORICAL-DB-NAME}
spring.datasource.username=${HISTORICAL_DB_USER_NAME}
spring.datasource.password=${HISTORICAL_DB_PASSWORD}

#Buy-Again properties
buy.again.list.size=50
buy.again.home.size=3

#product-sku double attributes
product.sku.double.attributes=THICKNESS,WIDTH,LENGTH,DIAMETER

ct.connection.timeout.seconds=200
ct.write.timeout.seconds=60
ct.read.timeout.seconds=120
ct.error.retry.count=3

#uom data storage
measurement.data.table.name=${MEASUREMENT-DATA-TABLE-NAME}

# material master
material.master.access.token=${MATERIAL_MASTER_ACCESS_TOKEN}
master.data.admin.api.key=${MASTER-DATA-ADMIN-PRODUCT-SERVICE-API-KEY:29a6541a-c456-4d64-a11e-daf98759b953}
material.master.base.url=${MATERIAL_MASTER_BASE_URL:https://master-data-admin.jsw1msme.in}
material.master.admin.client.id=${MATERIAL_MASTER_ADMIN_PRODUCT_SERVICE_CLIENT_ID:46705d34-550f-4c03-9d9b-19f20f906a46}
master.data.service.base.url=${MASTER_DATA_SERVICE_CLOUD_RUN_URL:https://master-data.jsw1msme.in}
master.data.service.client.id=${MASTER_DATA_SERVICE_PRODUCT_SERVICE_CLIENT_ID:dbea3b33-f9f9-4860-829d-725e9c11f135}
mm.categoryInfo.url=/master_data_admin/api/material_master/v1/search?mmid=
master.data.service.moq.url=/master_data_service/api/v1/material/moq
master.data.service.api.key=${MASTER-DATA-PRODUCT-SERVICE-API-KEY:d0a85483-db3b-4c26-98dd-22227c37cd88}

#cashBack Service
cashback.service.base.url=${CASHBACK-SERVICE-CLOUD-RUN-URL}
cashback.pdp.static.response.url=/cashback-service/cashback/pdp
cashback.pdp.response.url=/cashback-service/cashback/pdp-price
cashback.cart.change.endpoint=/cashback-service/cashback/cart/change
cashback.enabled=${CASHBACK_ENABLED:true}
cashback.service.api.key=${CASHBACK-API-KEY}

#cache config
cached.category.list=61235c5d-2455-4456-a6b0-dd0bc7f806fd,30268079-05e9-4c64-8c99-d8823041e67b,27b9b4c9-5057-4f21-8a12-f5821a11aa59,d671d1f3-6642-4c0a-8472-e2315912fde3,\
  74e84482-9ffb-46a7-aff2-5189fe76d813,ff3a185b-dfb2-452d-89d2-ed8ff8f60ed5,dd8d43a1-7865-4825-8cf3-38637b0a83c0,66ae1237-88be-45c2-bfac-7d297177dfed,\
  9b57499e-053d-4530-adfc-9364e313f2cd,4099a216-dd94-4b68-8814-aa875ab59573,4957b60e-0346-424d-82dc-25b916d7db1f,\
  16ca209d-254a-4e53-8ba2-69962ed2c397,cd4559ed-c84f-4bb2-bf86-0cb2fb2b8fd4,626bf253-7cd1-46e7-ad99-6fe418940f43,5b9b41cf-9ad3-4487-afaf-53fc5c5315f3,\
  5e9ea38b-7fd9-499a-932e-cba8e25526a4,763da992-8ff6-44b4-acdd-1f8bf9517994,422989d2-0743-4377-909a-94af3e7055fa,144bd177-c27a-430e-9d54-d56f243f0162,\
  f4622efc-7cf0-42da-b415-ce426e009ba1,ff8167da-2ef6-4333-83cf-42403c36eb0d,5f4f808c-4d8c-4fe5-96fc-e785cffde4a8,816ba07b-072c-4cfe-870b-1fd18b0838a3,\
  858aeaeb-78e4-48d1-bc23-a60e434acc59,8547fef3-2af5-42d2-9876-d40ddd8146fc,842addaf-18d9-454e-86be-09f5e298d8f8,61aab04c-d7b9-43a7-9cec-0addcbf6db70,\
  8df0b37c-cea9-4d0d-a667-124b6ecd7a9a,87423129-9d1e-4cf8-aa26-5befcefe40fb,6f07f4bf-0417-49f6-85a6-a7aa0610498c,a3648841-2170-44ac-aa57-b0ae281473a7,\
  1d60dbce-2471-4df7-9ed3-98207706736d,ff07654c-7f56-4294-8b71-ea87d1d22b22,75c6ccda-f68d-48bd-8b86-55d03a0db1fa,10a46dd5-33fe-4c9d-b813-986077837d57,\
  2e3b708d-57e0-492e-92f6-7f6026a06583,65b2382f-9a7f-4d45-a07b-3d4e7ae4323e,9b028343-632c-4ef8-b6f7-02366f580705,c04fd80e-691b-4f7e-b392-46108f545ded,\
  e7a6013a-c2d0-49c6-a6b5-600b50c7cb80,76b82714-e42f-4e03-a14f-439c7bfb5c61,cd4559ed-c84f-4bb2-bf86-0cb2fb2b8fd4,bb1a6d0c-c058-4a5f-a54f-d86be4804aee,\
  4a872fd2-301b-45cc-a544-2ecc04eabc19,cce52198-473b-4c56-a9cf-73c86b71af20,5b9b41cf-9ad3-4487-afaf-53fc5c5315f3,8547fef3-2af5-42d2-9876-d40ddd8146fc,\
  dbd894c7-9555-4212-afdf-58dccafc8a9a,92c8a5c6-9db2-424c-b8f2-2e075ec08a8d
cache.ttl=${CACHE-TTL}

entity.tmt.bb.charge-group = bending_bundling_charge_qa

order.service.base.url=${ORDER-SERVICE-CLOUD-RUN-URL}
order.service.historical.sku.endpoint=/order-service/requirement/buy-again/sku

#Auto Product
auto.product.failure.channel.id=${PRODUCT-CATEGORY-FAILURE-SLACK-CHANNEL:C073CRKAM3J}
product.category.store.table.name=product_category_validity_table
auto.product.creation.subscription=${AUTO-PRODUCT-MASTERS-SUBSCRIPTION:masters-auto-product-event-ccp-qa-sub}
pdp.breadcrumbs.enabled=${PDP_BREADCRUMBS_ENABLED:true}

#Tax Rate Table
entity.tax-rate-group = product_tax_rate_table_qa

#Salesforce CT Sync Service
auto.product.creation.salesforce.ctSync.url=${SALESFORCE-SERVICE-CLOUD-RUN-URL:https://salesforce-sync-service-qa-01-nonjw7c6va-el.a.run.app}/data-sync/product/add-product/salesforce


pricing.service.base.url=${PRICING-ENGINE-SERVICE-CLOUD-RUN-URL:https://pricing-qa.onejswmsme.in}
pricing.service.fetch.price.endpoint=/price-orchestrator/api/v1/pricing/priceList
pricing.service.api.key=${PRICING-ENGINE-PRODUCT-SERVICE-API-KEY:2cadb302-947b-4b4d-9fbd-076c8734bc35}
pricing.engine.integration.enabled=${PRICING-ENGINE-ENABLE-FLAG:true}
pricing.error.slack.channel.id=C071AFG6LP2
CHANNEL-API-KEY-MAPPINGS=[{"distributorCtId":"e4895bc9-44f6-4d54-b671-7503166890ae","vendorMasterId":"V1146-1147-JOPL-1147","sellerUniqueId":"JD001","channelKey":"JODLMH001"},{"distributorCtId":"c2af3774-baef-48b3-bff1-6f96070f3db6","vendorMasterId":"V1146-1322-JOPL-1322","sellerUniqueId":"JD002","channelKey":"JODLKA001"},{"distributorCtId":"93f12800-d747-43f8-b2e9-6fa99bd5bc4a","vendorMasterId":"V1146-1323-JOPL-1323","sellerUniqueId":"JD003","channelKey":"JODLTN001"}]
product.projection.search.enabled=${PRODUCT_PROJECTION_SEARCH_ENABLED}
plp.datastore.filter.enabled=${PLP_DATASTORE_FILTER_ENABLED:true}


product.service.strapi.enabled=${STRAPI_ENABLED:true}
product.service.user.strapi.enabled=${STRAPI_LIST_OF_USERS}

#API KEY PRODUCT SERVICE
api.key.product.service=${PRODUCT_SERVICE_API_KEY:ProductService-v1-7gd82kfjw5m3x9lzqypvoah64tsr0cnbxu1ejvdkf2h7w3miolbcqzfn6yp45t8}

buy.again.moq.enable=${ENABLE_MOQ_BUY_AGAIN:false}
product.service.pdp.journey.enabled=${PDP_JOURNEY_ENABLED:true}

#Teams Alert
pricing.error.teams.channel.workflow.url=${PRICING_ERROR_CHANNEL_WORKFLOW_URL:https://default1250f2eb4784422398dcd6e3344556.5c.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/f998f4bfe9044da685e1d7a49dd65d50/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=TmXxuowUQgHVDjavZSk-WL8VWmJp_vXXZpyRwxsrGJA}
auto.product.failure.teams.channel.workflow.url=${AUTO_PRODUCT_ERROR_CHANNEL_WORKFLOW_URL:https://default1250f2eb4784422398dcd6e3344556.5c.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/cb4a5516efa243d8995dc0fb0bb0ccb6/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=fjG6NMDaVwWyh4tB7uuaiuDfRtEcch_5M7_FV5LfaxM}
product.selector.datastore.flag=${PRODUCT_SELECTOR_DATA_STORE_FLAG:true}