package com.jswone.commerce.core.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum MaterialMasterToCTAttribute {
    DIAMETER("DIAMETER_MM"),
    DIAMETER_G("DIAMETER_GAUGE"),
    THICKNESS("THICKNESS_MM"),
    LENGTH( "LENGTH_MM"),
    LENGTH_M("LENGTH_M"),
    COATING_GRADE_GSM("S_ZN_COATING_GSM_MIN"),
    COATING_GRADE_GSM_AL("S_AL_ZN_COATING_GSM_MIN"),
    SPANGLE_TYPE("SPANGLE_TYPE"),
    FINISH("SURFACE_FINISH"),
    TMT_FORM("TMT_FORM"),
    TMT_FORM_P("PRODUCT_FORM"),
    BOX_SIZE("BOX_SIZE_KG"),
    BOX_SIZE_P("PACK_SIZE_KG"),
    SECTIONAL_WEIGHT("SECTIONAL_WEIGHT_KG_PER_M"),
    WEB_DEPTH("WEB_DEPTH_MM"),
    LEG("LEG1_MM"),
    WIDTH("WIDTH_MM"),
    FLANGE_WIDTH("FLANGE_WIDTH_MM"),
    CUT_LENGTH("CUT_LENGTH_MM"),
    COLOUR("S_COLOUR_CODE_TOP"),
    COLOUR_P("PAINT_COLOUR"),
    HEIGHT("HEIGHT_MM"),
    DEPTH("DEPTH_MM"),
    NOMINAL_BORE("NOMINAL_BORE_MM"),
    SERIES("SERIES_ENUM"),
    OUTSIDE_DIAMETER("OUTSIDE_DIAMETER_MM"),
    END_CONDITION("END_CONDITION"),
    PACKAGING_TYPE("PACKAGING_LTR"),
    TOP_COATING_GSM("TOP_COATING_GSM"),
    BOTTOM_COATING_GSM("BOTTOM_COATING_GSM");
    private final String materialMasterCTAttribute;

}
